### PR TITLE
Old widget layout as alternative

### PR DESCRIPTION
**Pull request by tilaktilak**
Related Issue : #1 
Pass default Instrument Panel from `QGCInstrumentWidgetAlternate.qml` to `QGCInstrumentWidget .qml`
Upate `QGCInstrumentWidgetAlternate` to retrieve a layout similar to the old version : 
image

Add a settings to switch from one to another :
image

### CODE REVIEW

**Comment by edwinhayes** [comment]
0. Is the box checked by default?  Otherwise the mainline probably won't accept a PR.
1. Does the setting of the checkbox persist correctly when the application is restarted?
2. Does the layout still behave sanely when the application font size is changed?
3. I think it's still now quite concentric?  Looks like the inner part needs to move maybe one pixel right?
4. The checkbox "Use alternate instrument panel layout": replace 'alternate' with something more self explanatory, 'side-by-side' or 'horizontal'.

**Comment by tilaktilak** [comment]
`1.  Is the box checked by default? Otherwise the mainline probably won't accept a PR.`

Box has to be checked to activate "our" layout, so it's unchecked by default. I thought that our modification can be an option but not the default setting, what do you think ?

`2. Does the setting of the checkbox persist correctly when the application is restarted?`

Yes, tested it.

`3. Does the layout still behave sanely when the application font size is changed?`

Looks OK

`4. I think it's still now quite concentric? Looks like the inner part needs to move maybe one pixel right?`


It was something due to my window manager, went back to unity.
I've also found some cropping issues while resizing the window
Working on it ! 
`5.  The checkbox "Use alternate instrument panel layout": replace 'alternate' with something more self explanatory, 'side-by-side' or 'horizontal'.`

As I mention what I call Alternate is the "stacked" version, not the one from master. Is '**Use vertical instrument panel layout**' ok ?

**Comment by edwinhayes** [comment]
Yup, that's the desired default behaviour: basically, PRs into the community version need to always leave the UI in the 'normal' configuration that existing users will be expecting.  On the other hand, once we have our own build system in place, we will probably want to make it so that the default settings for Aeronavics' builds are different.

And yeah, I misunderstood sorry; "vertical layout" is fine.

**Comment by tilaktilak** [comment]
Took me a while to fix the resizing issue, I sticked to the old version behaviour : Stretch the Text area.

**Comment by edwinhayes** [comment]
This seems legit now; per our discussion, leave this PR open for the mean time, but open another PR against the mainline.

**Comment by edwinhayes** [comment]
This can be closed out now yes?

**Comment by tilaktilak** [comment]
Added to mainline

**Pull request closed without merging**
